version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      environment:
        -DATABASE_URL=postgresql://postgres:postgres@db:5432/db
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db
